# Generated by Django 4.2 on 2023-04-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='facilitor',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
    ]
